# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fe4453270defbe279c33050fd04da88b8c0591065e97b949ca0b540f7eb840f83431b74e93b020bc1a8effc0b1926d5dad82201f4d45ca8b272d2dba4f1cde8

test:
  secret_key_base: e15ba193893b9f18d9c999b36baf61b90c99f399f908cd69c7b2db09eade92a8ebfcd5efa34e663bb7c147ce769e8cbc49b7ab6635e7cf39d6cf201c95c740f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
